import 'dart:typed_data';
import 'dart:convert';

/// Generador de comandos ESC/POS para impresoras térmicas de 80mm.
/// Implementación manual para evitar conflictos de dependencias.
class EscPosGenerator {
  final List<int> _bytes = [];

  // -- ESC/POS Command Constants --
  static const int _esc = 0x1B;
  static const int _gs = 0x1D;
  static const int _lf = 0x0A;

  /// Initialize printer
  EscPosGenerator() {
    _bytes.addAll([_esc, 0x40]); // ESC @ - Initialize
  }

  /// Set text alignment: 0=left, 1=center, 2=right
  void setAlign(int align) {
    _bytes.addAll([_esc, 0x61, align]);
  }

  /// Set text size. width and height are multipliers (1-8)
  void setTextSize({int width = 1, int height = 1}) {
    final n = ((width - 1) << 4) | (height - 1);
    _bytes.addAll([_gs, 0x21, n]);
  }

  /// Set bold on/off
  void setBold(bool on) {
    _bytes.addAll([_esc, 0x45, on ? 1 : 0]);
  }

  /// Set underline: 0=off, 1=1dot, 2=2dot
  void setUnderline(int n) {
    _bytes.addAll([_esc, 0x2D, n]);
  }

  /// Print text and feed line
  void printLine(String text) {
    _bytes.addAll(latin1.encode(text));
    _bytes.add(_lf);
  }

  /// Print text without line feed
  void printText(String text) {
    _bytes.addAll(latin1.encode(text));
  }

  /// Feed n lines
  void feed(int lines) {
    for (int i = 0; i < lines; i++) {
      _bytes.add(_lf);
    }
  }

  /// Print a horizontal separator line
  void printSeparator({String char = '-', int length = 48}) {
    printLine(char * length);
  }

  /// Print two columns (left-aligned and right-aligned)
  void printTwoColumns(String left, String right, {int totalWidth = 48}) {
    final spaces = totalWidth - left.length - right.length;
    if (spaces > 0) {
      printLine('$left${' ' * spaces}$right');
    } else {
      printLine('$left $right');
    }
  }

  /// Print QR code using ESC/POS QR commands
  void printQR(String data, {int moduleSize = 6, int errorCorrection = 49}) {
    final dataBytes = utf8.encode(data);
    final length = dataBytes.length + 3;
    final pL = length % 256;
    final pH = length ~/ 256;

    // QR: Select model
    _bytes.addAll([_gs, 0x28, 0x6B, 4, 0, 49, 65, 50, 0]);

    // QR: Set module size
    _bytes.addAll([_gs, 0x28, 0x6B, 3, 0, 49, 67, moduleSize]);

    // QR: Set error correction level (48=L, 49=M, 50=Q, 51=H)
    _bytes.addAll([_gs, 0x28, 0x6B, 3, 0, 49, 69, errorCorrection]);

    // QR: Store data
    _bytes.addAll([_gs, 0x28, 0x6B, pL, pH, 49, 80, 48]);
    _bytes.addAll(dataBytes);

    // QR: Print stored QR
    _bytes.addAll([_gs, 0x28, 0x6B, 3, 0, 49, 81, 48]);
  }

  /// Cut paper (partial cut)
  void cut() {
    _bytes.addAll([_gs, 0x56, 0x01]);
  }

  /// Full cut
  void fullCut() {
    _bytes.addAll([_gs, 0x56, 0x00]);
  }

  /// Open cash drawer (if connected)
  void openDrawer() {
    _bytes.addAll([_esc, 0x70, 0x00, 0x19, 0xFA]);
  }

  /// Get the generated bytes
  Uint8List getBytes() {
    return Uint8List.fromList(_bytes);
  }

  /// Reset (clear buffer)
  void reset() {
    _bytes.clear();
    _bytes.addAll([_esc, 0x40]);
  }
}
